name: CI-CD

on: 
    push:
      branches: ["main"]
    workflow_dispatch:

jobs:
    CI:
      runs-on: unbuntu-latest
      steps:
        - name: Checkout do repositorio 
          uses: actions/checkout@v5.0.0
        - name: Autenticação no Docker
          uses: docker/login-action@v3.5.0
          with:
              username: ${{secrets.DOCKERHUB_USERNAME}}
              password: ${{secrets.DOCKERHUB_TOKEN}}
        - name: Checkout do repositorio 
          uses: docker/build-push-action@v6.18.0
          with:
              context: ./src 
              file: ./src/Dockerfile
              push: true
              tags:
                  decioajr/devops4dev-news:v${{github.run_number}}
          
        - name: "Publicar a imagem no Docker Hub"
          run: echo "Docker push"
    CD:
      needs: [CI]
      runs-on: unbuntu-lastest
      steps:
        - name: Conectar com Kubernetes
          run: echo "Configraução do Kubeinf"
        - name: Executar Deploy
          run: echo "Kubectl apply"
