name: CI-CD

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Autenticando o usuario Docker
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Construindo a imagem e enviando para o DockerHub   
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            decioajr/devops4dev-news:latest
            decioajr/devops4dev-news:v${{github.run_number}}
             
            
  CD:
    runs-on: ubuntu-latest
    needs: CI
    
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositorio
      - name: Configuracao do Ambiente AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:  
          aws-region: "us-east-1"
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET}}
      - name: Configuração do KubeConfig
        run: aws eks update-kubeconfig --name devops4devs-eks --region us-east-1
      - name: Atualização Manifesto
        shell: bash
        run: |
          sed -i "s#{{AWS_ACCESS_KEY}}#${{ secrets.AWS_ACCESS_KEY }}#g" ./k8s/deploy.yaml
          sed -i "s#{{AWS_ACCESS_SECRET}}#${{ secrets.AWS_ACCESS_SECRET }}#g" ./k8s/deploy.yaml
      - name: Deploy manifests
        run: |
          kubectl apply -f ./k8s/deploy.yaml --namespace default
          
          
          
           
